name: SAM Deploy

on:
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build -t image-moderation/template.yaml --config-file image-moderation/samconfig.toml
      - run: sam deploy -t image-moderation/template.yaml --config-file image-moderation/samconfig.toml --parameter-overrides ModerationNotificationTopic=${{ vars.MODERATION_NOTIFICATION_TOPIC }} ModerationNotificationEndpoint=${{ vars.MODERATION_NOTIFICATION_ENDPOINT }}